// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGeneration.ServerCodeGenerator.Templates
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\reps\Dev.Template.AspNetCore\CodeGeneration\ServerCodeGenerator\Templates\ControllerTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    internal partial class ControllerTemplate : ControllerTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Common.Enums;
using Common.Search;
using BL;
using UI.Areas.Admin.Models;
using UI.Areas.Admin.Models.ViewModels;
using UI.Other;

namespace UI.Areas.Admin.Controllers
{
	[Area(""Admin"")]
	[Authorize(Roles = nameof(UserRole.Admin))]
	public class ");
            
            #line 19 "E:\reps\Dev.Template.AspNetCore\CodeGeneration\ServerCodeGenerator\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityDescription.PluralName));
            
            #line default
            #line hidden
            this.Write("Controller : Controller\r\n\t{\r\n\t\tpublic async Task<IActionResult> Index(int page = " +
                    "1)\r\n\t\t{\r\n\t\t\tconst int objectsPerPage = 20;\r\n\t\t\tvar searchResult = await new ");
            
            #line 24 "E:\reps\Dev.Template.AspNetCore\CodeGeneration\ServerCodeGenerator\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityDescription.PluralName));
            
            #line default
            #line hidden
            this.Write("BL().GetAsync(new ");
            
            #line 24 "E:\reps\Dev.Template.AspNetCore\CodeGeneration\ServerCodeGenerator\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityDescription.PluralName));
            
            #line default
            #line hidden
            this.Write("SearchParams\r\n\t\t\t{\r\n\t\t\t\tStartIndex = (page - 1) * objectsPerPage,\r\n\t\t\t\tObjectsCou" +
                    "nt = objectsPerPage,\r\n\t\t\t});\r\n\t\t\tvar viewModel = new SearchResultViewModel<");
            
            #line 29 "E:\reps\Dev.Template.AspNetCore\CodeGeneration\ServerCodeGenerator\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityDescription.Name));
            
            #line default
            #line hidden
            this.Write("Model>(");
            
            #line 29 "E:\reps\Dev.Template.AspNetCore\CodeGeneration\ServerCodeGenerator\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityDescription.Name));
            
            #line default
            #line hidden
            this.Write(@"Model.FromEntitiesList(searchResult.Objects), 
				searchResult.Total, searchResult.RequestedStartIndex, searchResult.RequestedObjectsCount, 5);
			return View(viewModel);
		}

		public async Task<IActionResult> Update(int? id)
		{
			var model = new ");
            
            #line 36 "E:\reps\Dev.Template.AspNetCore\CodeGeneration\ServerCodeGenerator\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityDescription.Name));
            
            #line default
            #line hidden
            this.Write("Model();\r\n\t\t\tif (id != null)\r\n\t\t\t{\r\n\t\t\t\tmodel = ");
            
            #line 39 "E:\reps\Dev.Template.AspNetCore\CodeGeneration\ServerCodeGenerator\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityDescription.Name));
            
            #line default
            #line hidden
            this.Write("Model.FromEntity(await new ");
            
            #line 39 "E:\reps\Dev.Template.AspNetCore\CodeGeneration\ServerCodeGenerator\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityDescription.PluralName));
            
            #line default
            #line hidden
            this.Write("BL().GetAsync(id.Value));\r\n\t\t\t\tif (model == null)\r\n\t\t\t\t\treturn NotFound();\r\n\t\t\t}\r" +
                    "\n\t\t\treturn View(model);\r\n\t\t}\r\n\r\n\t\t[HttpPost]\r\n\t\t[ValidateAntiForgeryToken]\r\n\t\tpu" +
                    "blic async Task<IActionResult> Update(");
            
            #line 48 "E:\reps\Dev.Template.AspNetCore\CodeGeneration\ServerCodeGenerator\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityDescription.Name));
            
            #line default
            #line hidden
            this.Write("Model model)\r\n\t\t{\r\n\t\t\tif (!ModelState.IsValid)\r\n\t\t\t{\r\n\t\t\t\treturn View(model);\r\n\t\t" +
                    "\t}\r\n\t\t\tawait new ");
            
            #line 54 "E:\reps\Dev.Template.AspNetCore\CodeGeneration\ServerCodeGenerator\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityDescription.PluralName));
            
            #line default
            #line hidden
            this.Write("BL().AddOrUpdateAsync(");
            
            #line 54 "E:\reps\Dev.Template.AspNetCore\CodeGeneration\ServerCodeGenerator\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityDescription.Name));
            
            #line default
            #line hidden
            this.Write("Model.ToEntity(model));\r\n\t\t\tTempData[OperationResultType.Success.ToString()] = \"Д" +
                    "анные сохранены\";\r\n\t\t\treturn RedirectToAction(\"Index\");\r\n\t\t}\r\n\r\n\t\tpublic async T" +
                    "ask<IActionResult> Delete(int id)\r\n\t\t{\r\n\t\t\tvar result = await new ");
            
            #line 61 "E:\reps\Dev.Template.AspNetCore\CodeGeneration\ServerCodeGenerator\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityDescription.PluralName));
            
            #line default
            #line hidden
            this.Write("BL().DeleteAsync(id);\r\n\t\t\tif (result)\r\n\t\t\t\tTempData[OperationResultType.Success.T" +
                    "oString()] = \"Объект удален\";\r\n\t\t\telse\r\n\t\t\t\tTempData[OperationResultType.Error.T" +
                    "oString()] = \"Объект не найден\";\r\n\t\t\treturn RedirectToAction(\"Index\");\r\n\t\t}\r\n\t}\r" +
                    "\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 70 "E:\reps\Dev.Template.AspNetCore\CodeGeneration\ServerCodeGenerator\Templates\ControllerTemplate.tt"

	internal EntityDescription EntityDescription;
	internal int MaxLineWidth;
	internal ControllerTemplate(EntityDescription entityDescription, int maxLineWidth) {
		EntityDescription = entityDescription;
		MaxLineWidth = maxLineWidth;
	}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    internal class ControllerTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
